// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: kqyzhtzlsoqbvbmldhdo

class SupabaseConfig {
  static const String supabaseUrl = 'https://kqyzhtzlsoqbvbmldhdo.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxeXpodHpsc29xYnZibWxkaGRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5NDQyMTEsImV4cCI6MjA3NjUyMDIxMX0.e6Nk4SpYFWc_Mpf7Rfx5iBX433hfZvEg9c1Gm7ssDG4';
}
